function image_normalize(Source, Destination, Width, Height, Extension)
    hApp = gcf;
    hWB = waitbar(0, strrep(strrep(Source, '\', '\\'), '_', '\_'), 'Name', 'Image Normalize');
    
    file = dir(fullfile(Source, strcat('*.', Extension)));
    count = numel(file);
    for index = 1 : count
        set(0, 'CurrentFigure', hWB);
        waitbar((index/count), hWB, strrep(file(index).name, '_', '\_'));
        set(0, 'CurrentFigure', hApp);
        
        image = imread(strcat(Source, filesep, file(index).name));  
%         buffer = size(image);
%         
%         imwrite( ...
%             imcrop(image, [ ...
%                 ((buffer(2) - Width) / 2) ...
%                 ((buffer(1) - Height) / 2) ...
%                 Width Height ...
%             ]), ...
%             strcat(Destination, filesep, file(index).name) ...
%         );

        imwrite( ...
            imresize(image, [Width Height]), ...
            strcat(Destination, filesep, file(index).name) ...
        );
    end
            
    close(hWB);
    set(0, 'CurrentFigure', hApp);
end